/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_ABSTRACTSTUBSERVER_H_
#define JSONRPC_CPP_STUB_ABSTRACTSTUBSERVER_H_

#include <jsonrpccpp/server.h>

class AbstractStubServer : public jsonrpc::AbstractServer<AbstractStubServer>
{
    public:
        AbstractStubServer(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<AbstractStubServer>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("sayHello", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_STRING,  NULL), &AbstractStubServer::sayHelloI);
            this->bindAndAddMethod(jsonrpc::Procedure("exeAlgorithm", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_INTEGER, "algorithm",jsonrpc::JSON_STRING,"computeRatio",jsonrpc::JSON_REAL,"rawfile",jsonrpc::JSON_STRING, NULL), &AbstractStubServer::exeAlgorithmI);
            this->bindAndAddMethod(jsonrpc::Procedure("stopListening", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_INTEGER,  NULL), &AbstractStubServer::stopListeningI);
        }

        inline virtual void sayHelloI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->sayHello();
        }
        inline virtual void exeAlgorithmI(const Json::Value &request, Json::Value &response)
        {
            response = this->exeAlgorithm(request["algorithm"].asString(), request["computeRatio"].asDouble(), request["rawfile"].asString());
        }
        inline virtual void stopListeningI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->stopListening();
        }
        virtual std::string sayHello() = 0;
        virtual int exeAlgorithm(const std::string& algorithm, double computeRatio, const std::string& rawfile) = 0;
        virtual int stopListening() = 0;
};

#endif //JSONRPC_CPP_STUB_ABSTRACTSTUBSERVER_H_
